### ISSUE TITLE
Add yotubers via list file 

### ISSUE THREAD

**Issue by TATUMTOT** [Xosrov/YouTube-Indexer#2]
Anyway to add the links via file based method. So i could point to the same file that is being used by youtube-dl

Other then that great job.

**Comment by Xosrov** [comment]
I'll be sure to add that to the next update. but as a temporary solution you could use something like this in a bash environment if channel names are separated by newline in your file.
`<file.txt xargs -d '\n' python3 collector.py -c`
If you don't have bash just wait for the next update, it won't be long.

Thanks

**Comment by Xosrov** [comment]
Added this feature in the new update. If you encounter any problems please open a new issue. 
Thanks
