### ISSUE TITLE
Getting a JSONDecodeError while consenting to YouTube

### ISSUE THREAD

**Issue by whokn3w** [Xosrov/YouTube-Indexer#3]
This is such a great little tool.  Thank you so much for creating it.  I've been having difficulties with the new YouTube consent update though.  I receive the following error when trying to run the command:

Consenting to YouTube...
Traceback (most recent call last):
  File "collector.py", line 502, in <module>
    sample = Collector(args.format, args.location,
  File "collector.py", line 42, in __init__
    self.consent()
  File "collector.py", line 50, in consent
    page_data_a = json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 133066 (char 133065)

**Comment by Xosrov** [comment]
Thanks for reporting this. YouTube slightly changed the HTML layout. I updated the code and it should work as expected. If there are no problems, please close this issue.

**Comment by DnanaDev** [comment]
@Xosrov The update has resulted in a new error. I am using the Collector class in another CLI script. When I run my script I get the following exception:

Consenting to YouTube...
'interstitial'
YouTube might have changed site format. if re-running the script didn't work, contact me to update the code (position 2.0)

**Comment by Xosrov** [comment]
@DnanaDev I don't get any errors when i test it. It might be possible that the HTML content isn't the same in every region.  
I've added basic logging to the code so it should produce log files in case something goes wrong. These include the HTML source returned by the YouTube server when something important goes wrong. 

Unfortunately this also includes personal information like your IP and region, but nothing specific as only essentials are transmitted to the server. If you prefer, use a VPN service and provide the log file in case it happens again.

In the meantime you could use the previous version of the script if that still works.

**Comment by whokn3w** [comment]
Yeah, I'm getting the same error as @DnanaDev.  After starting the script it gives me:

Consenting to YouTube...
'interstitial'

The log file then shows the following:

[error_log_20_54_05_11_2021.log](https://github.com/Xosrov/YouTube-Indexer/files/7489447/error_log_20_54_05_11_2021.log)

**Comment by Xosrov** [comment]
It seems YouTube doesn't require consent in some regions (i tested Canada).
Added a simple condition check before attempting consent. Please test the new commit and let me know if there are problems.

**Comment by whokn3w** [comment]
That did the trick!  Thank you so much for taking the time to update this application.  Such a handy tool and pleased to have it working again.  Will close this issue now that it's been fixed.
