### ISSUE TITLE
Youtube Might have changes site format

### ISSUE THREAD

**Issue by DnanaDev** [Xosrov/YouTube-Indexer#4]
I have been running this tool as part of my Youtube backup script and it has been working great!

However, I got this error recently and it looks like the page layout has changed.

_'sectionListRenderer'
YouTube might have changed site format. if re-running the script didn't work, contact me to update the code (position 2.3)_

**Comment by Xosrov** [comment]
Hey, thanks for reaching out. I updated the code for the new YouTube layout. 

Please test it and let me know if you run into any problems.

**Comment by DnanaDev** [comment]
That fixed it, Thanks!
